env:
  browser: true
  es2021: true
  react-native/react-native: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react-native
  - '@typescript-eslint'
rules: {
  import/prefer-default-import: "off",
  react/prop-types: "off",
}
