# Generated by Django 4.0.5 on 2022-06-14 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record_sheet', '0003_alter_assessment_options_alter_child_options_and_more'),
        ('invitations', '0004_invitation_school_alter_invitation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Pozvánka', 'verbose_name_plural': 'Pozvánky'},
        ),
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.CharField(choices=[('manager', 'Správce'), ('headmaster', 'Ředitel'), ('teacher', 'Učitel')], default='manager', max_length=10, verbose_name='Pozice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Akceptováno'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pozívající'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='record_sheet.school', verbose_name='Školka'),
        ),
    ]
