# Generated by Django 4.0.5 on 2022-06-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invitations', '0005_alter_invitation_options_alter_invitation_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='auth.group', verbose_name='Pozice'),
        ),
    ]
