# Generated by Django 4.0.3 on 2022-04-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('allows_note', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.category')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easier', '-'), ('same', '='), ('harder', '+')], max_length=50, null=True)),
                ('expected_age_from', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_age_to', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.assessmenttype')),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record_sheet.task')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('parent_assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.assessmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assessment', models.DateField()),
                ('note', models.TextField(null=True)),
                ('assessed_by', models.TextField(default='Dummy')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.assessmenttypeoption')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.task')),
            ],
        ),
    ]
