# Generated by Django 4.0.5 on 2022-06-13 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0002_invoice_parameter_school_cin_alter_child_school_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Hodnocení úkolu', 'verbose_name_plural': 'Hodnocení úkolů'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Dítě', 'verbose_name_plural': 'Děti'},
        ),
        migrations.AlterModelOptions(
            name='childnote',
            options={'verbose_name': 'Poznámka', 'verbose_name_plural': 'Poznámky o dětech'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Třída', 'verbose_name_plural': 'Třídy'},
        ),
        migrations.AlterModelOptions(
            name='classroomnote',
            options={'verbose_name': 'Poznámka', 'verbose_name_plural': 'Poznámky o třídách'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Položka faktury', 'verbose_name_plural': 'Položky faktury'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parametr', 'verbose_name_plural': 'Parametry'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Školka', 'verbose_name_plural': 'Školky'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Uživatel', 'verbose_name_plural': 'Uživatelé'},
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assessmenttypeoption',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_subscriber',
            field=models.BooleanField(default=True, verbose_name='Odběratel'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hodnotící'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='record_sheet.child', verbose_name='Dítě'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_of_assessment',
            field=models.DateField(verbose_name='Datum hodnocení'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='note',
            field=models.TextField(null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.assessmenttypeoption', verbose_name='Hodnocení'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.task', verbose_name='Úkol'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birthdate',
            field=models.DateField(verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='child',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='record_sheet.classroom', verbose_name='Třída'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.TextField(verbose_name='Křestní jméno'),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Muž'), ('F', 'Žena')], max_length=1, verbose_name='Pohlaví'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.TextField(verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='record_sheet.school', verbose_name='Školka'),
        ),
        migrations.AlterField(
            model_name='childnote',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='record_sheet.child', verbose_name='Dítě'),
        ),
        migrations.AlterField(
            model_name='childnote',
            name='note',
            field=models.TextField(verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='label',
            field=models.TextField(verbose_name='Třída'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='record_sheet.school', verbose_name='Školka'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Učitelé'),
        ),
        migrations.AlterField(
            model_name='classroomnote',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='record_sheet.classroom', verbose_name='Třída'),
        ),
        migrations.AlterField(
            model_name='classroomnote',
            name='note',
            field=models.TextField(verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum vystavení'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(verbose_name='Datum splatnosti'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Zaplaceno'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum zaplacení'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='record_sheet.school', verbose_name='Školka'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.IntegerField(verbose_name='Sériové číslo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Celková cena'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.IntegerField(verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Základ'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Název položky'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Celkem s DPH'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jednotková cena'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Sazba DPH'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.TextField(verbose_name='hodnota'),
        ),
    ]
