# Generated by Django 4.0.4 on 2022-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0002_category_is_in_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assessmenttypeoption',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_in_demo',
            field=models.BooleanField(null=True),
        ),
    ]
