# Generated by Django 4.0.3 on 2022-04-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0002_alter_task_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_text',
            new_name='task_description',
        ),
        migrations.AddField(
            model_name='task',
            name='codename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_age_from',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_age_to',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record_sheet.subcategory'),
        ),
    ]
