# Generated by Django 4.0.3 on 2022-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0003_rename_task_text_task_task_description_task_codename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('EASIER', '-'), ('SAME', '='), ('HARDER', '+')], max_length=50, null=True),
        ),
    ]
