# Generated by Django 4.0.4 on 2022-06-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0003_alter_assessment_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Hodnocení úkolu', 'verbose_name_plural': 'Hodnocení úkolů'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Dítě', 'verbose_name_plural': 'Děti'},
        ),
        migrations.AlterModelOptions(
            name='childnote',
            options={'verbose_name': 'Poznámka', 'verbose_name_plural': 'Poznámky o dětech'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Třída', 'verbose_name_plural': 'Třídy'},
        ),
        migrations.AlterModelOptions(
            name='classroomnote',
            options={'verbose_name': 'Poznámka', 'verbose_name_plural': 'Poznámky o třídách'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Škola', 'verbose_name_plural': 'Školy'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Uživatel', 'verbose_name_plural': 'Uživatelé'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hodnotitel'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.child', verbose_name='Dítě'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_of_assessment',
            field=models.DateField(verbose_name='Datum hodnocení'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='note',
            field=models.TextField(null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.assessmenttypeoption', verbose_name='Hodnocení'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_sheet.task', verbose_name='Úkol'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birthdate',
            field=models.DateField(verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='child',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='record_sheet.classroom', verbose_name='Třída'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.TextField(verbose_name='Rodné jméno'),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Muž'), ('F', 'Žena')], max_length=1, verbose_name='Pohlaví'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.TextField(verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='record_sheet.school', verbose_name='Škola'),
        ),
        migrations.AlterField(
            model_name='childnote',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='record_sheet.child', verbose_name='Dítě'),
        ),
        migrations.AlterField(
            model_name='childnote',
            name='note',
            field=models.TextField(verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='label',
            field=models.TextField(verbose_name='Třída'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='record_sheet.school', verbose_name='Škola'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Učitelé'),
        ),
        migrations.AlterField(
            model_name='classroomnote',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='record_sheet.classroom', verbose_name='Třída'),
        ),
        migrations.AlterField(
            model_name='classroomnote',
            name='note',
            field=models.TextField(verbose_name='Poznámka'),
        ),
    ]
