# Generated by Django 4.0.5 on 2022-06-17 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0003_alter_assessment_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Učitel', 'verbose_name_plural': 'Učitelé'},
        ),
        migrations.AddField(
            model_name='school',
            name='is_prepaid',
            field=models.BooleanField(default=False, verbose_name='Faktura vystavena dříve'),
        ),
        migrations.AlterField(
            model_name='childnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='childnote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='child_note_created_by', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil(a)'),
        ),
        migrations.AlterField(
            model_name='childnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='aktualizováno'),
        ),
        migrations.AlterField(
            model_name='childnote',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='child_note_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='aktualizoval(a)'),
        ),
        migrations.AlterField(
            model_name='classroomnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='classroomnote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='clsrm_note_created_by', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil(a)'),
        ),
        migrations.AlterField(
            model_name='classroomnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='aktualizováno'),
        ),
        migrations.AlterField(
            model_name='classroomnote',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='clsrm_note_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='aktualizoval(a)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='adresa'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mailová adresa'),
        ),
    ]
