# Generated by Django 4.0.4 on 2022-06-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0004_alter_assessment_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Školka', 'verbose_name_plural': 'Školky'},
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='record_sheet.school', verbose_name='Školka'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='record_sheet.school', verbose_name='Školka'),
        ),
    ]
