# Generated by Django 4.0.4 on 2022-06-06 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0005_alter_school_options_alter_child_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hodnotící'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.TextField(verbose_name='Křestní jméno'),
        ),
    ]
