# Generated by Django 4.0.4 on 2022-06-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0002_invoice_parameter_school_cin_alter_child_school_and_more'),
        ('record_sheet', '0006_alter_assessment_assessed_by_alter_child_first_name'),
    ]

    operations = [
    ]
