# Generated by Django 4.0.4 on 2022-06-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0007_merge_20220610_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Položka faktury', 'verbose_name_plural': 'Položky faktury'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parametr', 'verbose_name_plural': 'Parametry'},
        ),
        migrations.AddField(
            model_name='school',
            name='is_subscriber',
            field=models.BooleanField(default=True, verbose_name='Odběratel'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='record_sheet.child', verbose_name='Dítě'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='record_sheet.school', verbose_name='Školka'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum vystavení'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(verbose_name='Datum splatnosti'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Zaplaceno'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum zaplacení'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='record_sheet.school', verbose_name='Školka'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.IntegerField(verbose_name='Sériové číslo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Celková cena'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.IntegerField(verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Základ'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Název položky'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Celkem s DPH'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jednotková cena'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Sazba DPH'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.TextField(verbose_name='hodnota'),
        ),
    ]
