# Generated by Django 4.0.4 on 2022-06-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0009_router'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Router',
            new_name='ImportData',
        ),
    ]
