# Generated by Django 4.0.4 on 2022-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0010_rename_router_importdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importdata',
            name='specifications',
        ),
        migrations.AddField(
            model_name='importdata',
            name='children_csv',
            field=models.FileField(null=True, upload_to='uploads/csv_children'),
        ),
        migrations.AddField(
            model_name='importdata',
            name='school_csv',
            field=models.FileField(null=True, upload_to='uploads/csv_schools'),
        ),
    ]
