# Generated by Django 4.0.4 on 2022-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0011_remove_importdata_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='children_csv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/csv_children'),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='school_csv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/csv_schools'),
        ),
    ]
