# Generated by Django 4.0.4 on 2022-06-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0012_alter_importdata_children_csv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importdata',
            options={'verbose_name': 'ImportCSV', 'verbose_name_plural': 'ImportCSV'},
        ),
    ]
