# Generated by Django 4.0.4 on 2022-06-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_sheet', '0013_alter_importdata_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportData',
        ),
    ]
