assessment_type_options_help_table = [
    [254, "zvládá s dopomocí", "Nezvládá / zvládá s dopomocí / zvládá samostatně"],
    [254, "zvládá samostatně", "Nezvládá / zvládá s dopomocí / zvládá samostatně"],
    [254, "Nezvládá", "Nezvládá / zvládá s dopomocí / zvládá samostatně"],
    [255, "zvládá s dopomocí, ukáže obrázek", "Nezvládá / zvládá s dopomocí, ukáže obrázek / zvládá samostatně"],
    [255, "zvládá samostatně", "Nezvládá / zvládá s dopomocí, ukáže obrázek / zvládá samostatně"],
    [255, "Nezvládá", "Nezvládá / zvládá s dopomocí, ukáže obrázek / zvládá samostatně"],
    [256, "slovné hodnocení", "slovné hodnocení"],
    [257, "levá ruka", "pravá ruka / levá ruka / ruce střídá"],
    [257, "ruce střídá", "pravá ruka / levá ruka / ruce střídá"],
    [257, "pravá ruka", "pravá ruka / levá ruka / ruce střídá"],
    [258, "levé oko", "pravé oko / levé oko / oči střídá"],
    [258, "oči střídá", "pravé oko / levé oko / oči střídá"],
    [258, "pravé oko", "pravé oko / levé oko / oči střídá"],
    [259, "vyhraněná, praváctví, leváctví", "nevyhraněná / vyhraněná, praváctví, leváctví"],
    [259, "nevyhraněná", "nevyhraněná / vyhraněná, praváctví, leváctví"],
    [260, "ukáže na formátu", "Nezvládá / ukáže v prostoru, na sobě / ukáže na formátu / pojmenuje"],
    [260, "pojmenuje", "Nezvládá / ukáže v prostoru, na sobě / ukáže na formátu / pojmenuje"],
    [260, "ukáže v prostoru, na sobě", "Nezvládá / ukáže v prostoru, na sobě / ukáže na formátu / pojmenuje"],
    [260, "Nezvládá", "Nezvládá / ukáže v prostoru, na sobě / ukáže na formátu / pojmenuje"],
    [261, "ukáže s dopomocí, ukáže na obrázku", "Nezvládá / ukáže s dopomocí, ukáže na obrázku / zvládá samostatně, aktivně používá"],
    [261, "zvládá samostatně, aktivně používá", "Nezvládá / ukáže s dopomocí, ukáže na obrázku / zvládá samostatně, aktivně používá"],
    [261, "Nezvládá", "Nezvládá / ukáže s dopomocí, ukáže na obrázku / zvládá samostatně, aktivně používá"],
    [262, "zvládá s dopomocí, předmět přiřadí", "nezvládá / zvládá s dopomocí, předmět přiřadí / zvládá samostatně, pojmenuje"],
    [262, "zvládá samostatně, pojmenuje", "nezvládá / zvládá s dopomocí, předmět přiřadí / zvládá samostatně, pojmenuje"],
    [262, "nezvládá", "nezvládá / zvládá s dopomocí, předmět přiřadí / zvládá samostatně, pojmenuje"],
    [263, "zvládá s dopomocí", "Nezvládá / zvládá s dopomocí / zvládá samostatně, pojmenuje"],
    [263, "zvládá samostatně, pojmenuje", "Nezvládá / zvládá s dopomocí / zvládá samostatně, pojmenuje"],
    [263, "Nezvládá", "Nezvládá / zvládá s dopomocí / zvládá samostatně, pojmenuje"],
    [264, "zvládá s dopomocí, seřadí, ale nepojmenuje", "nezvládá / zvládá s dopomocí, seřadí, ale nepojmenuje / zvládá samostatně, pojmenuje"],
    [264, "zvládá samostatně, pojmenuje", "nezvládá / zvládá s dopomocí, seřadí, ale nepojmenuje / zvládá samostatně, pojmenuje"],
    [264, "nezvládá", "nezvládá / zvládá s dopomocí, seřadí, ale nepojmenuje / zvládá samostatně, pojmenuje"],
    [265, "zvládá s dopomocí, přiřadí", "nezvládá / zvládá s dopomocí, přiřadí / zvládá samostatně, pojmenuje"],
    [265, "zvládá samostatně, pojmenuje", "nezvládá / zvládá s dopomocí, přiřadí / zvládá samostatně, pojmenuje"],
    [265, "nezvládá", "nezvládá / zvládá s dopomocí, přiřadí / zvládá samostatně, pojmenuje"],
]